version: '3'
services:
  nginx:
    image: ghcr.io/ufal/dockerized-nginx-with-shibboleth/nginx-shib:latest
    restart: unless-stopped
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
    # generate /ssl/dhparam.pem with openssl dhparam -out dhparam.pem 4096
      - ./nginx/locations:/etc/nginx/locations
      - ./nginx/ssl:/ssl
    environment:
      - NGINX_ENVSUBST_FILTER=NGINX_
      - NGINX_SHIBAUTHORIZER=${NGINX_SHIBAUTHORIZER:-shibboleth:12344}
      - NGINX_SHIBRESPONDER=${NGINX_SHIBRESPONDER:-shibboleth:12345}
      - NGINX_TOMCAT
      - NGINX_NODE
      - NGINX_SERVER_NAMES
      - NGINX_RESOLVERS
      # this configures client_max_body_size only for the repository /server location
      - NGINX_MAX_BODY_SIZE=${NGINX_MAX_BODY_SIZE:-10G}
    depends_on:
      - shibboleth

  shibboleth:
    image: ghcr.io/ufal/dockerized-nginx-with-shibboleth/shibboleth:latest
    restart: unless-stopped
    build: ./shibboleth
    volumes:
    # config (+key material), logs
    - ./shibboleth/overrides:/overrides
    - ./shibboleth/sp-keys:/sp-keys
    - logs:/opt/shibboleth-sp/var/log
    environment:
     - SHIB_HOSTNAME=${SHIB_HOSTNAME:?SHIB_HOSTNAME must be set}

  syslog:
    image: cr.fluentbit.io/fluent/fluent-bit:latest
    restart: unless-stopped
    volumes:
      - ./fluent-bit/config.conf:/fluent-bit/etc/fluent-bit.conf
      - logs:/logs
    ports:
      - "5140:5140/udp"

volumes:
  logs:
